# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginR', '0003_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='departfrom',
            new_name='departdate',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='to',
            new_name='until',
        ),
    ]
